name = "github-proxy"
main = "github.js"
compatibility_date = "2026-07-24"

[cache]
enabled = true

[exports.default]
type = "worker"

  [exports.default.cache]
  enabled = false

[exports.CachedGitHubProxy]
type = "worker"

  [exports.CachedGitHubProxy.cache]
  enabled = true

[vars]
PROXY_HOSTNAME = "github.com"
RELEASE_PATHNAME_REGEX = "^/[^/]+/[^/]+/releases/download/[^/]+/.+"
GITHUB_RAW_PATHNAME_REGEX = "^/[^/]+/[^/]+/raw/.+"
UA_WHITELIST_REGEX = "^(curl|wget)"
