name = "docker-proxy"
main = "docker.js"
compatibility_date = "2026-07-24"

[cache]
enabled = true

[exports.default]
type = "worker"

  [exports.default.cache]
  enabled = false

[exports.CachedRegistryProxy]
type = "worker"

  [exports.CachedRegistryProxy.cache]
  enabled = true
